#!/usr/bin/env bash
# ============================================================
# Warehouse CRM — Automated Smoke Test
# ============================================================
# Prerequisites: jq (brew install jq), curl
# Usage: ./scripts/smoke-test.sh [BASE_URL]
# ============================================================

set -euo pipefail

BASE=${1:-http://localhost:3000}
API="${BASE}/api/v1"
PASS=0
FAIL=0
TOTAL=0

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

check() {
  TOTAL=$((TOTAL + 1))
  local label="$1"
  local expected="$2"
  local actual="$3"
  if [ "$actual" = "$expected" ]; then
    echo -e "  ${GREEN}✓ PASS${NC} — $label (got: $actual)"
    PASS=$((PASS + 1))
  else
    echo -e "  ${RED}✗ FAIL${NC} — $label (expected: $expected, got: $actual)"
    FAIL=$((FAIL + 1))
  fi
}

check_gte() {
  TOTAL=$((TOTAL + 1))
  local label="$1"
  local min="$2"
  local actual="$3"
  if [ "$actual" -ge "$min" ] 2>/dev/null; then
    echo -e "  ${GREEN}✓ PASS${NC} — $label (got: $actual, min: $min)"
    PASS=$((PASS + 1))
  else
    echo -e "  ${RED}✗ FAIL${NC} — $label (expected >= $min, got: $actual)"
    FAIL=$((FAIL + 1))
  fi
}

echo -e "\n${CYAN}═══════════════════════════════════════════${NC}"
echo -e "${CYAN}  Warehouse CRM — Smoke Test Suite${NC}"
echo -e "${CYAN}  Target: ${BASE}${NC}"
echo -e "${CYAN}═══════════════════════════════════════════${NC}\n"

# ─── 0. Health Check ─────────────────────────────────────────
echo -e "${YELLOW}[0/9] Health Check${NC}"
HEALTH=$(curl -s "${BASE}/health")
STATUS=$(echo "$HEALTH" | jq -r '.status')
check "GET /health → status=ok" "ok" "$STATUS"

# ─── 1. Register Admin ───────────────────────────────────────
echo -e "\n${YELLOW}[1/9] Register Admin User${NC}"
REG=$(curl -s -w "\n%{http_code}" -X POST "${API}/auth/register" \
  -H "Content-Type: application/json" \
  -d '{"username":"smoke_admin","password":"smoke123","role":"admin"}')
REG_BODY=$(echo "$REG" | head -1)
REG_CODE=$(echo "$REG" | tail -1)

# Accept 201 (new) or 409 (already exists)
if [ "$REG_CODE" = "201" ] || [ "$REG_CODE" = "409" ]; then
  echo -e "  ${GREEN}✓ PASS${NC} — Register returned HTTP $REG_CODE"
  PASS=$((PASS + 1))
else
  echo -e "  ${RED}✗ FAIL${NC} — Register returned HTTP $REG_CODE"
  FAIL=$((FAIL + 1))
fi
TOTAL=$((TOTAL + 1))

# ─── 2. Login → Extract TOKEN ────────────────────────────────
echo -e "\n${YELLOW}[2/9] Login & Extract JWT Token${NC}"
LOGIN=$(curl -s -X POST "${API}/auth/login" \
  -H "Content-Type: application/json" \
  -d '{"username":"smoke_admin","password":"smoke123"}')
TOKEN=$(echo "$LOGIN" | jq -r '.token')
if [ -n "$TOKEN" ] && [ "$TOKEN" != "null" ]; then
  echo -e "  ${GREEN}✓ PASS${NC} — Got JWT token (${TOKEN:0:20}...)"
  PASS=$((PASS + 1))
else
  echo -e "  ${RED}✗ FAIL${NC} — No token received. Response: $LOGIN"
  FAIL=$((FAIL + 1))
  echo -e "\n${RED}Cannot continue without token. Aborting.${NC}\n"
  exit 1
fi
TOTAL=$((TOTAL + 1))

AUTH="Authorization: Bearer ${TOKEN}"

# ─── 3. Create Product ───────────────────────────────────────
echo -e "\n${YELLOW}[3/9] Create Product${NC}"
PROD=$(curl -s -X POST "${API}/products" \
  -H "Content-Type: application/json" \
  -H "$AUTH" \
  -d '{"sku":"SMOKE-001","name":"Smoke Test Widget","description":"Auto-generated by smoke test","unit":"pcs"}')
PID=$(echo "$PROD" | jq -r '.id')
if [ -n "$PID" ] && [ "$PID" != "null" ]; then
  echo -e "  ${GREEN}✓ PASS${NC} — Created product PID=$PID"
  PASS=$((PASS + 1))
else
  echo -e "  ${RED}✗ FAIL${NC} — Product creation failed. Response: $PROD"
  FAIL=$((FAIL + 1))
fi
TOTAL=$((TOTAL + 1))

# ─── 4. Create Location ──────────────────────────────────────
echo -e "\n${YELLOW}[4/9] Create Location${NC}"
LOC=$(curl -s -X POST "${API}/locations" \
  -H "Content-Type: application/json" \
  -H "$AUTH" \
  -d '{"code":"SMOKE-A-R1-S1","name":"Smoke Zone A Rack 1 Shelf 1","zone":"A","aisle":"1","rack":"R1","level":"S1"}')
LID=$(echo "$LOC" | jq -r '.id')
if [ -n "$LID" ] && [ "$LID" != "null" ]; then
  echo -e "  ${GREEN}✓ PASS${NC} — Created location LID=$LID"
  PASS=$((PASS + 1))
else
  echo -e "  ${RED}✗ FAIL${NC} — Location creation failed. Response: $LOC"
  FAIL=$((FAIL + 1))
fi
TOTAL=$((TOTAL + 1))

# ─── 5. Inbound +1000 ────────────────────────────────────────
echo -e "\n${YELLOW}[5/9] Inbound +1000${NC}"
INB=$(curl -s -X POST "${API}/inbound" \
  -H "Content-Type: application/json" \
  -H "$AUTH" \
  -d "{\"product_id\":\"${PID}\",\"location_id\":\"${LID}\",\"quantity\":1000,\"reference\":\"SMOKE-IN-001\"}")
INB_QTY=$(echo "$INB" | jq -r '.quantity')
check "Inbound quantity" "1000" "$INB_QTY"

# ─── 6. Check Stock = 1000 ───────────────────────────────────
echo -e "\n${YELLOW}[6/9] Verify Stock = 1000${NC}"
STOCK1=$(curl -s "${API}/stock/product/${PID}" -H "$AUTH")
QTY1=$(echo "$STOCK1" | jq -r '.data[0].quantity')
check "Stock after inbound" "1000" "$QTY1"

# ─── 7. Outbound -200 ────────────────────────────────────────
echo -e "\n${YELLOW}[7/9] Outbound -200${NC}"
OUT=$(curl -s -X POST "${API}/outbound" \
  -H "Content-Type: application/json" \
  -H "$AUTH" \
  -d "{\"product_id\":\"${PID}\",\"location_id\":\"${LID}\",\"quantity\":200,\"reference\":\"SMOKE-OUT-001\"}")
OUT_QTY=$(echo "$OUT" | jq -r '.quantity')
check "Outbound quantity" "200" "$OUT_QTY"

# ─── 8. Check Stock = 800 ────────────────────────────────────
echo -e "\n${YELLOW}[8/9] Verify Stock = 800${NC}"
STOCK2=$(curl -s "${API}/stock/product/${PID}" -H "$AUTH")
QTY2=$(echo "$STOCK2" | jq -r '.data[0].quantity')
check "Stock after outbound" "800" "$QTY2"

# ─── 9. History Records ──────────────────────────────────────
echo -e "\n${YELLOW}[9/9] Verify History Records${NC}"
HIST=$(curl -s "${API}/history" -H "$AUTH")
HIST_TOTAL=$(echo "$HIST" | jq -r '.total')
check_gte "History records exist" "2" "$HIST_TOTAL"

# ─── 10. Metrics Endpoint ────────────────────────────────────
echo -e "\n${YELLOW}[BONUS] Prometheus Metrics${NC}"
METRICS=$(curl -s "${BASE}/metrics" | head -1)
if echo "$METRICS" | grep -q "HELP\|TYPE\|http"; then
  echo -e "  ${GREEN}✓ PASS${NC} — /metrics returns Prometheus data"
  PASS=$((PASS + 1))
else
  echo -e "  ${RED}✗ FAIL${NC} — /metrics response unexpected: $METRICS"
  FAIL=$((FAIL + 1))
fi
TOTAL=$((TOTAL + 1))

# ─── Summary ─────────────────────────────────────────────────
echo -e "\n${CYAN}═══════════════════════════════════════════${NC}"
echo -e "  Results: ${GREEN}${PASS} passed${NC}, ${RED}${FAIL} failed${NC}, ${TOTAL} total"
echo -e "${CYAN}═══════════════════════════════════════════${NC}\n"

if [ "$FAIL" -gt 0 ]; then
  exit 1
fi
exit 0
